import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Oneisok",
  description: "Generated by create next app",
  icons: [
    { rel: "icon", url: "/oneisok.png", sizes: "16x16", type: "image/png" },
    { rel: "icon", url: "/oneisok-32.png", sizes: "32x32", type: "image/png" },
    { rel: "icon", url: "/oneisok-64.png", sizes: "64x64", type: "image/png" },
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable}`}
      >
          {children}
      </body>
    </html>
  );
}
